#
# Node Version Manager
#
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

#
# SSH - first, `scp ~/.ssh/newssh root@18.217.8.193:~/.ssh/newssh`
#
eval $(ssh-agent -s);
ssh-add ~/.ssh/newssh;

#
# hints
#
echo '
    NGINX:
    ne /etc/nginx/sites-available/default
    service nginx restart
';

